# Generated by Django 5.2.1 on 2025-07-10 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Укажите уникальный email', max_length=100, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Укажите имя', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Укажите фамилию', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите уникальный ник', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимое имя пользователя', regex='^[\\w.@+-]+\\Z')], verbose_name='Никнейм'),
        ),
    ]
